# Generated by Django 5.2.1 on 2025-05-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_code', models.CharField(max_length=4)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
