# Generated by Django 5.2.1 on 2025-06-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email_code',
            old_name='email_code',
            new_name='emailcode',
        ),
    ]
