# Generated by Django 5.2.1 on 2025-06-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authory', '0003_rename_emailcode_email_code_email_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email_code',
            old_name='email_code',
            new_name='emailcode',
        ),
    ]
